### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [nanamitoshimasu/studying_mate#100]
@nanamitoshimasu 

お疲れ様です！
こちらMVPリリース のレビューになります！

### 技術
GitHubを使ったログインや要所でのHotwireを入れるなど、しっかり技術を使っている印象でした。
上記を踏まえて以下、フィードバックとしてお伝えさせていただきます。
- `app/models/team.rb`の`image_for_time`メソッドで画像を出し分けているかと思うのですが、かなり冗長になっているかと思うので、送られてきた値を使って変数を作成し、 動的に変えてあげるとスッキリしそうです。
```
def image_for_time(num)
     animal_image =  if num.present?
                                    "image-#{num}.jpg"
                                  else
                                     "display_default.png"
                                  end
end
のような形でメソッドを作成し、animal_imageを使ってあげるといいと思います
(動作を確認していないため参考程度見ていただければと🙇)
```
- マジックナンバー等も気になったので、`gem rubocop`などをいれてLintチェックもするといいと思いました。
- 技術の追加はREADMEに記載してある「その後の機能」を中心に実装していきましょう。

### ユーザビリティ
独特の世界観をうまく表現できていて、ユーザビリティもわかりやすく作ってあると思います。
以下、ユーザビリティ面でのフィードバックになります。
- 世界観がある分、**何ができるアプリケーションなのか**ユーザに伝わりにくい面もあるかと思ったので、「使い方」のほうなコンテンツを用意してあげるといいかと思いました。(ここでも世界観を出せると良さそうです。)
- 現状、image画像も投稿できるかと思いますが、「絶滅危惧種を救う」というコンセプトがあるので、

 救う動物を選択 → 画像と学習時間が選んだ動物によって自動で選ばれる

のような機能にしても面白そうかと思いました。

以上です！
世界観がいい味を出して、楽しく学習に迎えるようなWebアプリになっているかと思います！

LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by nanamitoshimasu** [comment]
お疲れ様です。
レビューありがとうございます。

>現状、image画像も投稿できるかと思いますが、「絶滅危惧種を救う」というコンセプトがあるので、
>救う動物を選択 → 画像と学習時間が選んだ動物によって自動で選ばれる

こちらの機能すごくいいなと思いました。

私の認識が間違っていないか確認させてください。
現在:
- 募集記事に好きな画像を投稿が投稿できる
- 目標時間を選ぶと目標時間に応じた動物の画像が出てくる

変更後:
- 絶滅の危機から救いたい動物をユーザーが選べる
- その動物に応じた目標時間数の表示
- 画像はユーザーが投稿するのではなく、救う動物の画像を表示させ募集する

こういうことですよね？
確かに、好きな画像を載せるよりも絶滅危惧種の画像が一覧に並んでいるほうが世界観が出てめちゃくちゃいいなと思いました。

**Comment by tmtkzk0823** [comment]
> 変更後:
絶滅の危機から救いたい動物をユーザーが選べる
その動物に応じた目標時間数の表示
画像はユーザーが投稿するのではなく、救う動物の画像を表示させ募集する

はい！
上記にの認識であっています！🙌

**Comment by nanamitoshimasu** [comment]
少し余裕を持たせて本リリースは3/10にしようと思います。
よろしくお願いします。

**Comment by tmtkzk0823** [comment]
承知ししました！
実装頑張ってください！
